/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as InvestmentsIndexRouteImport } from './routes/investments.index'
import { Route as TransactionsNewRouteImport } from './routes/transactions.new'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'
import { Route as InvestmentsIbRouteImport } from './routes/investments.ib'
import { Route as TransactionsEditIdRouteImport } from './routes/transactions.edit.$id'

const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIndexRoute = InvestmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvestmentsRoute,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsIbRoute = InvestmentsIbRouteImport.update({
  id: '/ib',
  path: '/ib',
  getParentRoute: () => InvestmentsRoute,
} as any)
const TransactionsEditIdRoute = TransactionsEditIdRouteImport.update({
  id: '/transactions/edit/$id',
  path: '/transactions/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investments': typeof InvestmentsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/travel': typeof TravelRoute
  '/investments/ib': typeof InvestmentsIbRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/investments/': typeof InvestmentsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/travel': typeof TravelRoute
  '/investments/ib': typeof InvestmentsIbRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/investments': typeof InvestmentsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investments': typeof InvestmentsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/travel': typeof TravelRoute
  '/investments/ib': typeof InvestmentsIbRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/investments/': typeof InvestmentsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/investments'
    | '/settings'
    | '/travel'
    | '/investments/ib'
    | '/transactions/$id'
    | '/transactions/new'
    | '/investments/'
    | '/transactions/'
    | '/transactions/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/travel'
    | '/investments/ib'
    | '/transactions/$id'
    | '/transactions/new'
    | '/investments'
    | '/transactions'
    | '/transactions/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/investments'
    | '/settings'
    | '/travel'
    | '/investments/ib'
    | '/transactions/$id'
    | '/transactions/new'
    | '/investments/'
    | '/transactions/'
    | '/transactions/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestmentsRoute: typeof InvestmentsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TravelRoute: typeof TravelRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  TransactionsEditIdRoute: typeof TransactionsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/': {
      id: '/investments/'
      path: '/'
      fullPath: '/investments/'
      preLoaderRoute: typeof InvestmentsIndexRouteImport
      parentRoute: typeof InvestmentsRoute
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments/ib': {
      id: '/investments/ib'
      path: '/ib'
      fullPath: '/investments/ib'
      preLoaderRoute: typeof InvestmentsIbRouteImport
      parentRoute: typeof InvestmentsRoute
    }
    '/transactions/edit/$id': {
      id: '/transactions/edit/$id'
      path: '/transactions/edit/$id'
      fullPath: '/transactions/edit/$id'
      preLoaderRoute: typeof TransactionsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InvestmentsRouteChildren {
  InvestmentsIbRoute: typeof InvestmentsIbRoute
  InvestmentsIndexRoute: typeof InvestmentsIndexRoute
}

const InvestmentsRouteChildren: InvestmentsRouteChildren = {
  InvestmentsIbRoute: InvestmentsIbRoute,
  InvestmentsIndexRoute: InvestmentsIndexRoute,
}

const InvestmentsRouteWithChildren = InvestmentsRoute._addFileChildren(
  InvestmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestmentsRoute: InvestmentsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TravelRoute: TravelRoute,
  TransactionsIdRoute: TransactionsIdRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  TransactionsEditIdRoute: TransactionsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
