/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as InvestmentsRouteImport } from './routes/investments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as TransactionsNewRouteImport } from './routes/transactions.new'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'
import { Route as TransactionsEditIdRouteImport } from './routes/transactions.edit.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentsRoute = InvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/transactions/new',
  path: '/transactions/new',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsEditIdRoute = TransactionsEditIdRouteImport.update({
  id: '/transactions/edit/$id',
  path: '/transactions/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/investments': typeof InvestmentsRoute
  '/settings': typeof SettingsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investments': typeof InvestmentsRoute
  '/settings': typeof SettingsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/transactions': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/investments': typeof InvestmentsRoute
  '/settings': typeof SettingsRoute
  '/transactions/$id': typeof TransactionsIdRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/transactions/edit/$id': typeof TransactionsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/investments'
    | '/settings'
    | '/transactions/$id'
    | '/transactions/new'
    | '/transactions/'
    | '/transactions/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/investments'
    | '/settings'
    | '/transactions/$id'
    | '/transactions/new'
    | '/transactions'
    | '/transactions/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/investments'
    | '/settings'
    | '/transactions/$id'
    | '/transactions/new'
    | '/transactions/'
    | '/transactions/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InvestmentsRoute: typeof InvestmentsRoute
  SettingsRoute: typeof SettingsRoute
  TransactionsIdRoute: typeof TransactionsIdRoute
  TransactionsNewRoute: typeof TransactionsNewRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
  TransactionsEditIdRoute: typeof TransactionsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investments': {
      id: '/investments'
      path: '/investments'
      fullPath: '/investments'
      preLoaderRoute: typeof InvestmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/transactions/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/edit/$id': {
      id: '/transactions/edit/$id'
      path: '/transactions/edit/$id'
      fullPath: '/transactions/edit/$id'
      preLoaderRoute: typeof TransactionsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InvestmentsRoute: InvestmentsRoute,
  SettingsRoute: SettingsRoute,
  TransactionsIdRoute: TransactionsIdRoute,
  TransactionsNewRoute: TransactionsNewRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
  TransactionsEditIdRoute: TransactionsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
